In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])
x,c,v,b = a

In [29]:
c={'a':4}
def f(d):
    d['a'] = 5
    
c


{'a': 4}

In [40]:
a=[]
b=[np.array([1]),np.array([2])]

In [48]:
c=np.array([1])
np.hstack((c,np.array([2])))

array([1, 2])

In [1]:
a=[ {'n':1},{'n':1},{'n':2}, {'n':1}, {'n':2} ]

In [16]:
import os 
for i in range(5):
    l = os.listdir("/home/hyh/Documents/quanyi/project/Data/e_optha_MA/MA/VOC2012/JPEGImages")
    l.sort()
    print(l[-29:])

['DS000GH5.jpg', 'DS000GH6.jpg', 'DS000H04.jpg', 'DS000HVE.jpg', 'DS000HVG.jpg', 'DS000HVH.jpg', 'DS000HVI.jpg', 'DS000HXJ.jpg', 'DS000HXK.jpg', 'DS000HXL.jpg', 'DS000I6W.jpg', 'DS000I6X.jpg', 'DS000I6Z.jpg', 'DS000N9X.jpg', 'DS000N9Y.jpg', 'DS000N9Z.jpg', 'DS000NA1.jpg', 'DS000OQB.jpg', 'DS000QA2.jpg', 'DS000STU.jpg', 'DS000STW.jpg', 'DS000TZ5.jpg', 'DS000U30.jpg', 'DS000U4U.jpg', 'DS000V1O.jpg', 'DS000V1R.jpg', 'DS000V6O.jpg', 'DS000V6S.jpg', 'DS000VCN.jpg']
['DS000GH5.jpg', 'DS000GH6.jpg', 'DS000H04.jpg', 'DS000HVE.jpg', 'DS000HVG.jpg', 'DS000HVH.jpg', 'DS000HVI.jpg', 'DS000HXJ.jpg', 'DS000HXK.jpg', 'DS000HXL.jpg', 'DS000I6W.jpg', 'DS000I6X.jpg', 'DS000I6Z.jpg', 'DS000N9X.jpg', 'DS000N9Y.jpg', 'DS000N9Z.jpg', 'DS000NA1.jpg', 'DS000OQB.jpg', 'DS000QA2.jpg', 'DS000STU.jpg', 'DS000STW.jpg', 'DS000TZ5.jpg', 'DS000U30.jpg', 'DS000U4U.jpg', 'DS000V1O.jpg', 'DS000V1R.jpg', 'DS000V6O.jpg', 'DS000V6S.jpg', 'DS000VCN.jpg']
['DS000GH5.jpg', 'DS000GH6.jpg', 'DS000H04.jpg', 'DS000HVE.jpg', 'DS00

In [5]:
import numpy as np
a=np.array([1,2,3])

In [3]:
import 

array(['1', '2', '3'], dtype='<U21')

In [4]:
a.append('1')

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [3]:
def f():
    a=1
    def k():
        print(a)
    k()
print(a)
f()

NameError: name 'a' is not defined

In [8]:
from alive_progress import alive_bar
import time

items = range(100)
with alive_bar(len(items), title="Processing", bar="classic2", spinner="dots_waves2") as bar:
    for item in items:
        time.sleep(0.1)
        bar()

Processing [########################################] 100/100 [100%] in 10.0s (9.98/s) 


In [14]:
a=np.array([True,False])
a.any()

True

In [19]:
class abc:

    def func(self, **kwargs):
        print(kwargs)
        print(type(kwargs))
        
    def f3(self,f):
        f[0](a=1,b=2)
        
    def f2(self):
        self.f3([self.func])

abc_ = abc()
abc_.f2()


{'a': 1, 'b': 2}
<class 'dict'>


In [7]:
f=(Annotation_Txt_Dir='Annotations_Txt',)

SyntaxError: invalid syntax (2263201311.py, line 1)

In [18]:
f={'a':1}
'a' in f.keys()

True

In [19]:
a=[1,2,3,4]
b=a[0:2]
b[0]=4
a

[1, 2, 3, 4]

In [23]:
b=np.array([True,False])
a=np.array([True,True])
np.logical_and(a,b)

array([ True, False])

In [31]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
from tqdm import tqdm
import time

outer_iterations = 5
inner_iterations = 10
total_iterations = outer_iterations * inner_iterations

# 创建一个总的进度条
with tqdm(total=total_iterations, desc="Processing") as pbar:
    for i in range(outer_iterations):
        for j in range(inner_iterations):
            # 模拟一些工作
            time.sleep(0.1)
            # 每次内层循环迭代时更新进度条
            pbar.update(1)


Processing: 100%|██████████| 50/50 [00:05<00:00,  9.80it/s]


In [45]:
a=[12,3]
a*=2
a

[12, 3, 12, 3]

In [66]:
import random
import torch
a=np.array([[1],[2]])
# a=torch.tensor([1,2,3,4])
p=[]
for i in range(4):
    np.random.shuffle(a)
    print((a))
    p.append(a[:])
print(p)


[[1]
 [2]]
[[2]
 [1]]
[[1]
 [2]]
[[2]
 [1]]
[array([[2],
       [1]]), array([[2],
       [1]]), array([[2],
       [1]]), array([[2],
       [1]])]


In [37]:
a=np.array([[1],[2]])
print(np.average(a))


1.5


In [47]:
a=np.array([[1],[2]])
mask = [False,False]

In [48]:
if(a[mask]):
    print(1)

/tmp/ipykernel_35670/2246639128.py:1: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if(a[mask]):


In [50]:
a=[]
b=np.array([[1],[2]])
a.extend(b)
a

[array([1]), array([2])]

In [52]:
import json

x = [{'name':'你猜','age':19,'city':'四川'},{'name':'你猜','age':20,'city':'四川'}]

#把python编码成json放在那个文件里
filename = 'pi_x.json'
with open (filename,'a') as f:
    for i in x:
        json.dump(i,f)

In [54]:
import json

# 从 JSON 文件读取字典
with open('pi_x.json', 'r') as json_file:
    data = json.load(json_file)

print(data)

{'name': '你猜', 'age': 19, 'city': '四川'}


In [13]:
import numpy as np
a=np.array([[True,False],[False,False]])

In [1]:
a=[[1]]
b=['a',a]

In [3]:
c={"asd":4}
for k,v in c.items():
    if k.endswith('d'):
        print(1)

1


In [47]:
import numpy as np
a=np.array([[1,1],[2,2],[3,3]])
b=np.array([1,2,3,4])
mask=[True,True,False]
print(a[mask])
print(a[0:2])
a[mask][:,0]=4
a


[[1 1]
 [2 2]]
[[1 1]
 [2 2]]


array([[1, 1],
       [2, 2],
       [3, 3]])

In [53]:
a=[1,2,3]
b=a[:]
b[0]=4
a

[1, 2, 3]

In [54]:
a = [[1, 2], [3, 4], [5, 6]]
b = a[:]

# 修改 b 中的一个元素
b[0][0] = 10

print("Original list a:", a)
print("Sliced list b:", b)

Original list a: [[10, 2], [3, 4], [5, 6]]
Sliced list b: [[10, 2], [3, 4], [5, 6]]


In [55]:
a = [[1, 2], [3, 4], [5, 6]]
b = a[:]

# 替换 b 中的一个元素
b[0] = [10, 20]

print("Original list a:", a)
print("Sliced list b:", b)

Original list a: [[1, 2], [3, 4], [5, 6]]
Sliced list b: [[10, 20], [3, 4], [5, 6]]


In [110]:
a = [[1, 2], [3, 4], [5, 6]]
mask = [True,False,True]
b = a[:]
c = a
print("变量地址")
print(id(a))
print(id(b))
print(id(c))
print('内层变量地址')
for i in range(3):
    print(id(a[i]))
    print(id(c[i]))
    print(id(b[i]))
print('变量地址')
for i in range(3):
    print(id(a[i][0]))
    print(id(c[i][0]))
    print(id(b[i][0]))
    


变量地址
139736702734784
139736702737088
139736702734784
内层变量地址
139736702881280
139736702881280
139736702881280
139736702878464
139736702878464
139736702878464
139736365971904
139736365971904
139736365971904
变量地址
139736753920304
139736753920304
139736753920304
139736753920368
139736753920368
139736753920368
139736753920432
139736753920432
139736753920432


In [108]:
b[0] = [4,5]
a

[[1, 2], [3, 4], [5, 6]]

In [139]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
mask = [True, True, True]
b = a[:,:]
c = a.copy()
d = a[mask]

print("变量地址")
print(id(a))
print(id(b))
print(id(d))
print(id(c))

print("内层变量地址")
for ai,bi,di in zip(a,b,d):
    print(id(ai))
    print(id(bi))
    print(id(di))

print("元素地址")
for i in range(3):
    print(id(a[i][0]))
    print(id(b[i][0]))
    print(id(d[i][0]))
    
    
    
    
print("xiugai")
d[0] = [44,55]
b[0] = [55,66]

print("变量地址")
print(id(a))
print(id(b))
print(id(d))

print("内层变量地址")
for ai,bi,di in zip(a,b,d):
    print(id(ai))
    print(id(bi))
    print(id(di))

print("元素地址")
for i in range(3):
    print(id(a[i][0]))
    print(id(b[i][0]))
    print(id(d[i][0]))


print(a)
print(b)
print(d)
    

变量地址
139736365954320
139736365954416
139736365954704
139736365953456
内层变量地址
139736365954608
139736365954512
139736365954800
139736365954224
139736365953552
139736365954032
139736365954800
139736365954512
139736365954608
元素地址
139736365820080
139736365819792
139736365820080
139736365819792
139736365820080
139736365819792
139736365820080
139736365819792
139736365820080
xiugai
变量地址
139736365954320
139736365954416
139736365954704
内层变量地址
139736365954032
139736365953552
139736365954224
139736365954608
139736365954512
139736365954800
139736365954224
139736365953552
139736365954032
元素地址
139736365819568
139736365819952
139736365819568
139736365819952
139736365819568
139736365819952
139736365819568
139736365819952
139736365819568
[[55 66]
 [ 3  4]
 [ 5  6]]
[[55 66]
 [ 3  4]
 [ 5  6]]
[[44 55]
 [ 3  4]
 [ 5  6]]


In [205]:

a=True
print(~ a)

-2


In [165]:
a=np.array([[1,2,3,4]])
b=np.array([4,5,6])
a[:,0:3]+b

array([[5, 7, 9]])

In [178]:
a = np.array([])
b=np.array([4,5,6,7])
a.resize([a.shape[0],4])
a+b


array([], shape=(0, 4), dtype=float64)

In [182]:
a = np.array([])
a.resize([0,5])
print(a)

[]


In [191]:
b=np.array([4.453123,5.786456,6.45643,7.456123])

[4.453123 5.786456 6.45643  7.456123]


In [193]:
b[np.argmax(b)]


7.456123

In [18]:
b = a['a']
b=4

In [19]:
a

{'a': 2}

In [20]:
b

4

In [31]:
a=np.array([[True],[True]])
b=np.logical_not(a)

In [32]:
np.sum(a)

2

In [33]:
a=np.array([0,0,0,0])
b=np.array([1,2,3,4])
mask=[False,False,False,False]
np.max(a[mask])

ValueError: zero-size array to reduction operation maximum which has no identity

In [35]:
bool(0)

False

In [50]:
import json
class NumpyDecoder(json.JSONDecoder):
    def decode(self, s, **kwargs):
        result = super().decode(s, **kwargs)
        return self._convert(result)

    def _convert(self, obj):
        if isinstance(obj, list):
            try:
                return np.array(obj)
            except ValueError:
                return obj
        elif isinstance(obj, dict):
            return {key: self._convert(value) for key, value in obj.items()}
        return obj


In [2]:
a=[]
c="as"
d=1
e=[1,2,3]
a.append([c,d,e])

In [4]:
for c,d,e in a:
    print(c)
    print(d)
    print(e)

as
1
[1, 2, 3]


In [6]:
a=[1,2,3,4]
a[1:]

[2, 3, 4]

In [7]:
import torch
import torch.nn as nn

class SpatialPyramidPooling(nn.Module):
    def __init__(self, levels=[4, 2, 1]):
        super(SpatialPyramidPooling, self).__init__()
        self.levels = levels

    def forward(self, x):
        b, c, h, w = x.size()
        output = []

        for level in self.levels:
            kernel_size = (h // level, w // level)
            stride = kernel_size
            pooling = nn.AdaptiveMaxPool2d((level, level))
            pooled = pooling(x)  # 池化操作
            output.append(pooled.view(b, c, -1))  # 调整形状

        return output

# 示例用法
b, c, h, w = 1, 3, 32, 32
x = torch.randn(b, c, h, w)
spp = SpatialPyramidPooling(levels=[4, 2, 1])
output = spp(x)

for o in output:
    print(o.size())

torch.Size([1, 3, 16])
torch.Size([1, 3, 4])
torch.Size([1, 3, 1])


In [70]:
b

tensor([[1.]])